export const AJconsole = '控制台'

export const AJuserN = '用户管理'
export const AJusermatchN = '人员库匹配'
export const AJusermatchadd = '照片加入'
export const AJusermatchdel = '照片删除'
export const AJuseraddN = '用户添加'
export const AJusereditN = '用户编辑'
export const AJuserdelN = '用户删除'
export const AJuserimportN = '用户导入'
export const AJuserresetpassN = '密码重置'
export const AJuserbatchphotoN = '批量上传照片'
export const AJusersinglephotoN = '照片'

export const AJuserstudentN = '学生'

export const AJuserdeptN = '机构人员'

export const AJworkstationN = '巡视工作站'
export const AJworkstationaddN = '巡视工作站添加'
export const AJworkstationeditN = '巡视工作站编辑'
export const AJworkstationdelN = '巡视工作站删除'
export const AJworkstationrelN = '关联教室'

export const AJtermN = '学期管理'
export const AJtermaddN = '学期添加'
export const AJtermeditN = '学期编辑'
export const AJtermdelN = '学期删除'

export const AJroleN = '角色管理'
export const AJroleaddN = '角色添加'
export const AJroleeditN = '角色编辑'
export const AJroledelN = '角色删除'
export const AJpowerN = '角色授权'

export const AJcollegeN = '学院管理'
export const AJcollegeaddN = '学院添加'
export const AJcollegeeditN = '学院编辑'
export const AJcollegedelN = '学院删除'

export const AJclassmanageN = '班级管理'

export const AJclassnumberN = '节次表管理'
export const AJclassnumberaddN = '上课时间表添加'
export const AJclassnumbereditN = '上课时间表修改'
export const AJclassnumberdelN = '上课时间表删除'
export const AJclassnumberadddetailN = '节次添加'
export const AJclassnumbereditdetailN = '节次编辑'
export const AJclassnumberdeldetailN = '节次删除'
export const AJclassnumberdefaultN = '设为默认'

export const AJserverN = '服务器管理'
export const AJserveraddN = '服务器添加'
export const AJservereditN = '服务器编辑'
export const AJserverdelN = '服务器删除'
export const AJserverrelN = '关联教室'
export const AJserverstorerelN = '关联存储区'

export const AJlogN = '日志管理'
export const AJlogaddN = '日志添加'
export const AJlogeditN = '日志编辑'
export const AJlogdelN = '日志删除'

export const AJstoreN = '存储区管理'
export const AJstoreaddN = '存储区添加'
export const AJstoreeditN = '存储区编辑'
export const AJstoredelN = '存储区删除'

export const AJbuildingN = '教学楼教室管理'
export const AJbuildingaddN = '教学楼添加'
export const AJbuildingeditN = '教学楼编辑'
export const AJbuildingdelN = '教学楼删除'
export const AJbuildingadddetailN = '教室添加'
export const AJbuildingeditdetailN = '教室编辑'
export const AJbuildingdeldetailN = '教室删除'

export const AJdailyrecordN = '常态录播管理'
export const AJdailyrecordeditN = '教室编辑'
export const AJdailyrecordroomaddN = '教室添加'

export const AJloopClassN = '在线巡课'
export const AJloopClassseeN = '查看'


export const AJsmartClassroomN = '博瑞在线巡课'
export const AJstatisticsN = '考勤统计'
export const AJdiligenceN = '到勤率回顾'

export const AJbookmarkpageN = '智慧教室'

export const AJGroupLoopManageN = '巡课群组管理'
export const AJGroupLoopManageaddN = '巡课群组添加'
export const AJGroupLoopManageeditN = '巡课群组编辑'
export const AJGroupLoopManagedelN = '巡课群组删除'
export const AJGroupLoopManagerelassistantN = '辅导员'
export const AJGroupLoopManagerelassistantunpublishN = '取消设置为负责人'
export const AJGroupLoopManagerelassistantpublishN = '设置为负责人'
export const AJGroupLoopManagerelassistantdelN = '删除辅导员'
export const AJGroupLoopManagereladdN = '添加成员'
export const AJGroupLoopManagerelleaderN = '院系领导'
export const AJGroupLoopManagerelleaderunpublishN = '取消设置为负责人'
export const AJGroupLoopManagerelleaderpublishN = '设置为负责人'
export const AJGroupLoopManagerelleaderdelN = '删除院系领导'
export const AJGroupLoopManagerelotherN = '其他角色'
export const AJGroupLoopManagerelotherunpublishN = '取消设置为负责人'
export const AJGroupLoopManagerelotherpublishN = '设置为负责人'
export const AJGroupLoopManagerelotherdelN = '删除其他角色'

export const AJcontrolrecordN = '集控录播管理'
export const AJcontrolrecordaddN = '集控录播添加'
export const AJcontrolrecordeditN = '集控录播编辑'
export const AJcontrolrecorddelN = '集控录播删除'
export const AJcontrolrecordadddetailN = '通道添加'
export const AJcontrolrecordeditdetailN = '通道编辑'
export const AJcontrolrecorddeldetailN = '通道删除'
export const AJcontrolrecordJKLBroomaddN = '教室添加'
export const AJcontrolrecordsetchannelN = '通道标定'

export const AJcourseN = '校内课程'
export const AJcourseseeN = '查看'
export const AJcourseddN = '课程添加'
export const AJcourseeditN = '课程编辑'
export const AJcoursedelN = '课程删除'
export const AJcourseclassaddN = '章节添加'
export const AJcourseclasseditN = '章节编辑'
export const AJcoursedeldetailN = '章节删除'
export const AJcourseimportN = '课表导入'

export const AJlessonN = '课表'
export const AJlessonaddN = '课表添加'
export const AJlessonfreeaddN = '课表添加'
export const AJlessoneditN = '课表编辑'
export const AJlessondelN = '课表删除'

export const AJresourceN = '资源管理'
export const AJresourceeditN = '资源编辑'
export const AJresourcedelN = '资源删除'
export const AJresourcepowerN = '资源播放'
export const AJresourcedownN = '资源下载'
export const AJresourcepublishN = '资源发布'

export const AJmonitorN = '系统监控'
export const AJmonitorseeN = '查看'

export const AJappointN = '预约'
export const AJappointtimeN = '时间管理'
export const AJappointdetailN = '详情'
export const AJappointanounceN = '预约公告'
export const AJappointanounceaddN = '公告添加'
export const AJappointanounceeditN = '公告编辑'
export const AJappointanouncedelN = '公告删除'

export const AJappointManageN = '管理预约'
export const AJappointManageaddN = '预约审核'
export const AJappointManageeditN = '预约撤销'
export const AJappointManagedelN = '预约详情'

export const AJappointHistoryN = '历史纪录'
export const AJappointHistorydelN = '详情'

export const AJanalysisN = '统计分析'

export const AJcontroloperationN = '集中控制'
export const AJcontroloperationaddN = '录制开始'
export const AJcontroloperationstopN = '录制结束'
export const AJcontroloperationseeN = '巡课'
export const AJcontroloperationalterN = '确认录制信息'

export const AJattendRateN = '到勤率动态'
export const AJattendRateseeN = '查看详情'

export const AJdailyoperationN = '常态控制'

export const AJappointuserN = '用户预约'
export const AJappointuseraddN = '添加预约'
export const AJappointuserdetailN = '详情'
export const AJappointuserHistoryN = '预约记录'
export const AJappointuserHistorydetailN = '详情'

export const AJportalN = '门户管理'
export const AJportaleditN = '编辑门户'

export const AJannounceN = '公告'
export const AJannounceaddN = '公告添加'
export const AJannounceeditN = '公告编辑'
export const AJannouncedelN = '公告删除'

export const AJsubjectN = '学科'
export const AJsubjectaddN = '学科添加'
export const AJsubjecteditN = '学科编辑'
export const AJsubjectdelN = '学科删除'

export const AJstudySectionN = '学段'
export const AJstudySectionaddN = '学段添加'
export const AJstudySectioneditN = '学段编辑'
export const AJstudySectiondelN = '学段删除'
export const AJstudySectionrelN = '关联学科'

export const AJevaluateTemplateN = '评价模板'
export const AJevaluateTemplateaddN = '评价模板添加'
export const AJevaluateTemplateeditN = '评价模板编辑'
export const AJevaluateTemplatedelN = '评价模板删除'
export const AJevaluateTemplatepublishN = '评价模板发布'
export const AJevaluateTemplateunpublishN = '评价模板取消'

export const AJevaluateTemplateloopN = '巡课评价管理'
export const AJevaluateTemplateloopaddN = '巡课评价模板添加'
export const AJevaluateTemplateloopeditN = '巡课评价模板编辑'
export const AJevaluateTemplateloopdelN = '巡课评价模板删除'
export const AJevaluateTemplatelooppublishN = '巡课评价模板启用'
export const AJevaluateTemplateloopunpublishN = '巡课评价模板未启用'
export const AJevaluateTemplateloopsettemplateN = '巡课评价模板设置'
export const AJevaluateTemplateloopsettemplatedelN = '巡课评价题目删除'
export const AJevaluateTemplateloopsettemplateRadioaddN = '单选题添加'
export const AJevaluateTemplateloopsettemplateCheckaddN = '复选题添加'
export const AJevaluateTemplateloopsettemplateScoleaddN = '评分项添加'
export const AJevaluateTemplateloopsettemplateCountaddN = '计数题添加'
export const AJevaluateTemplateloopsettemplateQuestionaddN = '问答题添加'
export const AJevaluateTemplateloopsettemplateQuestioneditN = '问答题编辑'
export const AJevaluateTemplateloopsettemplateCounteditN = '计数题编辑'
export const AJevaluateTemplateloopsettemplateScoleeditN = '评分项编辑'
export const AJevaluateTemplateloopsettemplateCheckeditN = '复选题编辑'
export const AJevaluateTemplateloopsettemplateRadioeditN = '单选题编辑'
export const AJevaluateTemplateloopsettemplatereseeN = '评价表预览'

export const AJliveN = '直播管理'
export const AJliveaddN = '添加直播'
export const AJliveeditN = '编辑直播'
export const AJlivepowerN = '查看直播'
export const AJlivedownN = '下载资源'
export const AJlivedelN = '删除直播'
export const AJlivemasterN = '选择主持人'
export const AJlivebasicuploadN = '图片上传'
export const AJlivedownlistN = '资源下载'
export const AJliveseeN = '资源预览'
export const AJlivestopN = '停止直播'
export const AJlivereleaseN = '发布直播'

export const AJevaluateTemplatesettemplateN = '设置评价模板'
export const AJevaluateTemplatesettemplateaddN = '创建评价维度'
export const AJevaluateTemplatesettemplateeditN = '编辑评价维度'
export const AJevaluateTemplatesettemplatedelN = '删除评价维度'
export const AJevaluateTemplatesettemplatecontentaddN = '创建评价内容'
export const AJevaluateTemplatesettemplatecontenteditN = '编辑评价内容'
export const AJevaluateTemplatesettemplatecontentdelN = '删除评价内容'

export const AJcourseManageN = '课程管理'
export const AJcourseManagebasicuploadN = '选择图片'
export const AJcourseManagenoticeN = '公告管理'
export const AJcourseManagenoticeaddN = '公告添加'
export const AJcourseManagenoticeeditN = '公告编辑'
export const AJcourseManagenoticedelN = '公告删除'
export const AJcourseManagesynopsisN = '大纲管理'
export const AJcourseManagesynopsisdelN = '删除大纲'
export const AJcourseManagesynopsisaddN = '大纲添加'
export const AJcourseManagesynopsiseditN = '大纲编辑'
export const AJcourseManagechampterN = '章节管理'
export const AJcourseManagechampteraddN = '章节添加'
export const AJcourseManagechamptereditN = '章节编辑'
export const AJcourseManagechampterdelN = '章节删除'
export const AJcourseManagechampterrespublishN = '发布'
export const AJcourseManagechampterresunpublishN = '取消发布'
export const AJcourseManagechampterresdelN = '删除资源'
export const AJcourseManagechampterresaddN = '资源上传'
export const AJcourseManageresN = '资源管理'
export const AJcourseManageresaddN = '资源上传'
export const AJcourseManageresdelN = '资源删除'
export const AJcourseManageresseeN = '查看'
export const AJcourseManageresseepicN = '查看'
export const AJcourseManageresseeaudioN = '查看'
export const AJcourseManageresseepdfN = '查看'
export const AJcourseManageresdownlistN = '下载'
export const AJcourseManageresdownlistpicN = '下载'
export const AJcourseManageresmoveN = '资源移动'
export const AJcourseManagerespublishN = '发布资源'
export const AJcourseManageresunpublishN = '取消资源'
export const AJcourseManageteamN = '团队管理'
export const AJcourseManageteamaddN = '添加课程老师'
export const AJcourseManageteamdelN = '删除老师'
export const AJcourseManagebookN = '参考教材管理'
export const AJcourseManagebookaddN = '添加教材'
export const AJcourseManagebookeditN = '编辑教材'
export const AJcourseManagebookdelN = '删除教材'
export const AJcourseManagebookuploadN = '上传缩略图'

export const AJcourseOnlineN = '在线课程'
export const AJcourselessonlistN = '节次管理'
export const AJcourseOnlineaddN = '添加课程'
export const AJcourseOnlineeditN = '编辑课程'
export const AJcourseOnlinedelN = '删除课程'

export const AJlabelN = '标签组管理'
export const AJlabeladdN = '标签组添加'
export const AJlabeleditN = '标签组编辑'
export const AJlabeldelN = '标签组删除'
export const AJlabelcontentaddN = '标签组内容添加'
export const AJlabelcontenteditN = '标签组内容编辑'
export const AJlabelcontentdelN = '标签组内容删除'

// 模块管理
export const AJmoduleN = '模块管理'
export const AJmoduleeditN = '模块编辑'

// 课程筛选条件管理
export const AJcurriculumN = '课程筛选条件管理'
export const AJcurriculumimportN = '导入标签组'
export const AJcurriculumdelN = '删除筛选条件'

export const AJtoolN = '工具管理'
export const AJtoolseetranscodeN = '转码中'
export const AJtoolseetranscodedN = '已转码'
export const AJtoolseeN = '查看'
export const AJtooldelN = '删除'

// 用户中心
export const AJusercenterN = '用户中心'
export const AJusercentermeN = '个人资料'
export const AJusercenterfocusN = '我的关注'
export const AJusercentercollectN = '我收藏的资源'
export const AJusercenterbookN = '我收藏的课程'
export const AJusercentercollectdelN = '取消收藏'
export const AJusercenterbasicuploadN = '上传图片'

// 机构管理
export const AJorganizationN = '机构管理'
export const AJorganizationaddN = '机构管理添加'
export const AJorganizationeditN = '机构管理编辑'
export const AJorganizationdelN = '机构管理删除'

//学科管理
export const AJhighteachingN = '学科管理'


// 专业管理
export const AJmajorN = '专业管理'
export const AJmajoraddN = '专业管理添加'
export const AJmajoreditN = '专业管理编辑'
export const AJmajordelN = '专业管理删除'

// 职务管理
export const AJdutyN = '职务管理'
export const AJdutyaddN = '职务添加管理'
export const AJdutyeditN = '职务编辑管理'
export const AJdutydelN = '职务删除管理'

export const AJbannerN = '焦点图管理'
export const AJbanneraddN = '焦点图添加'
export const AJbannereditN = '焦点图编辑'
export const AJbannerdelN = '焦点图删除'
export const AJbannerunpublishN = '取消发布'
export const AJbannerpublishN = '发布'

export const AJrankmanageN = '模块管理'
export const AJrankmanageeditN = '模块编辑'

export const AJcampusTVchannelN = '频道管理'
export const AJcampusTVchanneladdN = '频道管添加'
export const AJcampusTVchanneleditN = '频道编辑'
export const AJcampusTVchanneldelN = '频道删除'

export const AJcampusTVlistN = '节目单管理'
export const AJcampusTVlistaddN = '节目添加'
export const AJcampusTVlistaddbasicuploadN = '图片上传'
export const AJcampusTVlisteditN = '节目单编辑'
export const AJcampusTVlisteditbasicuploadN = '图片上传'
export const AJcampusTVlistunpublishN = '取消发布'
export const AJcampusTVlistpublishN = '发布'
export const AJcampusTVlistdelN = '删除'
export const AJcampusTVlistcopyN = '复制节目单'

export const AJadministrativeclassN = '班级管理'
export const AJadministrativeclassaddN = '班级添加'
export const AJadministrativeclasseditN = '班级编辑'
export const AJadministrativeclassdelN = '班级删除'
export const AJadministrativeclassrelN = '辅导员添加'
export const AJadministrativeclassstlistN = '学生列表'
export const AJadministrativeclassstlistaddN = '学生添加'
export const AJadministrativeclassstlistdelN = '学生删除'

export const AJteachclassN = '教学班级管理'
export const AJteachclassstlistN = '学生列表'
export const AJteachclassstlistaddN = '学生添加'
export const AJteachclassstlistdelN = '学生删除'

export const AJintelligentterminalN = '智慧终端管理'
export const AJintelligentterminaleditN = '智慧终端编辑'
export const AJintelligentterminaladdN = '智慧终端添加'
export const AJintelligentterminaldelN = '智慧终端删除'

export const AJlogManage = '日志管理'
export const AJuserLibrary = '人员库'
export const AJuserLibraryMatchN = '人员库匹配'

export const FlivereviewN = '直播回顾'
export const FlivedownlistN = '直播回顾下载'


export const AJscheduleplanN = '课表'
