import {developUrl} from '@/module/admin/config/urlPage'
export const screenN = '筛选条件'
export const statusN = '状态'
export const settingN = '操作'
export const setOpenN = '设置为开放'
export const setCloseN = '设置为关闭'
export const openN = '开放'
export const closeN = '关闭'
export const saveN = '保存'
export const cancelN = '取消'
export const delN = '删除'
export const contentN = '确定要删除吗？'
export const screenImportN = '导入标签组'
export const screendelN = '删除筛选条件'
export const listhead = ['筛选条件', '状态', '操作']
export const percentinfo = ['wid30', 'wid20', 'wid50']
export const colums = ['name', 'status', 'opt']
export const pathinfo = {'prex': 'AJcurriculum', 'optname': '课程筛选条件'}
export const optobjinfoAll = ['设置为关闭', '删除']
export const opteventAll = ['close', 'dellist']
export const optobjinfoAllA = ['设置为打开', '删除']
export const opteventAllA = ['start', 'dellist']
export const products = []
export const infoval = []
export const bingos = []
export const pageval = 1
export const listurl =developUrl + '/control/course/findCourseScreens'
export const addurl = developUrl +'/control/course/addFromLabelGroups'
export const editurl = developUrl +'/control/course/openOrCloseCourseScreen'
export const delurl = developUrl +'/control/course/deleteCourseScreen'
export const exceptlist = developUrl +'/control/course/findExceptLabelGroups'
export const pagesize = 10
export const OsN = '设置为打开'
export const OdN = '删除'
export const OcN = '设置为关闭'
export const OPslist = 'start'
export const OPclist = 'close'
export const OPdlist = 'dellist'
export const pagestyles = ''

