import {developUrl,mockjs } from '@/module/admin/config/urlPage'
export const getMicroSubjectList =(mockjs == '' ? developUrl : mockjs ) + '/base/microSubject/getMicroSubjectList'
export const deleteMicroSubject =(mockjs == '' ? developUrl : mockjs ) + '/base/microSubject/deleteMicroSubject'
export const updateMicroSubject =(mockjs == '' ? developUrl : mockjs ) + '/base/microSubject/updateMicroSubject'
export const findMajorList =(mockjs == '' ? developUrl : mockjs ) + '/base/Major/findMajorList'
export const addMicroSubject =(mockjs == '' ? developUrl : mockjs ) + '/base/microSubject/addMicroSubject'
export const getMicroGradeList = developUrl  + '/base/microGrade/getMicroGradeList'
export const findMicroPushList = developUrl + '/learning/courseCenter/findMicroPushList'
export const addMicroPushClicks = developUrl + '/learning/courseCenter/addMicroPushClicks'
export const getMicroLessons = developUrl + '/learning/microLessonCenter/getMicroLessons'
