export const syN = '开始学年'
export const eyN = '结束学年'
export const termN = '学期'
export const sydateN = '开始日期'
export const eydateN = '结束日期'
export const saveN = '保存'
export const cancelN = '取消'
export const delN = '删除'
export const contentN = '确定要删除吗？'
export const msgaddN = '学期添加'
export const msgeditN = '学期编辑'
export const msgdelN = '学期删除'
export const listhead = ['check', '资源名称', '转换格式', '大小', '状态','开始时间' ,'所属服务','操作']
export const pathinfo = {'prex': 'AJtool', 'optname': '详情'}
export const optobjinfoAll = ['查看']
export const percentinfo = ['wid5', 'wid20', 'wid10', 'wid10', 'wid10', 'wid15','wid10','wid20']
export const colums = ['check', 'toolName', 'toolHost','toolType', 'toolPort', 'status', 'opt']
export const opteventAll = ['see']
export const products = []
export const infoval = []
export const bingos = []
export const searchinput = 'width:150px;'
export const searchstyle = 'width:300px;'
export const pageval = 1
export const listurl = '/base/tools/getToolTasks'
export const addurl = '/control/term/addTerm'
export const editurl = '/base/tools/getToolTasks'
export const delurl = '/control/term/deleteTerm'
export const pagesize = 10
export const OdN = '删除'
export const OaN = '添加'
export const OPalist = 'addlist'
export const OPelist = 'editlist'
export const OPdlist = 'dellist'