import {developUrl} from '@/module/admin/config/urlPage'
export const findUserLibClassesList = developUrl + '/base/classes/findUserLibClassesList'
export const getUnmatchStudentXml = developUrl + '/base/classesUserIcon/getUnmatchStudentXml'
export const delUserIconByXml = developUrl + '/base/classesUserIcon/delUserIconByXml'
export const findStudentImageListByClassID = developUrl + '/base/classes/findStudentImageListByClassID'
export const matchStudentImageList = developUrl + '/base/classesUserIcon/matchStudentImageList'
export const findAllUserLibClassesList = developUrl + '/base/classes/findAllUserLibClassesList'
export const findUserIconsByID = developUrl + '/base/user/findUserIconsByID'
export const deleteMatchStudentImage = developUrl + '/base/classesUserIcon/deleteMatchStudentImage'
