import {developUrl,moni} from '@/module/admin/config/urlPage'

export const findLessonsByDeviceIp = developUrl + 'learning/courseCenter/findLessonsByDeviceIp'
export const findStatusByDeviceIp = developUrl + 'learning/courseCenter/findStatusByDeviceIp'
export const getClassroomSeatFreeRate = developUrl + 'base/classroom/getClassroomSeatFreeRate'
export const getTeachingStyleIndex = (localStorage.getItem('moni')=="true"?'/moni':developUrl)  + '/base/classroom/getTeachingStyleIndex'
export const findTotalAiBrainStatus = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/base/classroom/findTotalAiBrainStatus'
export const findSchoolParticipateRateAvg = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/lessonInfo/findSchoolParticipateRateAvg'
export const findTermsLists = developUrl + '/control/term/findTermsLists'
export const classroomsCount = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/base/classroom/classroomsCount'
export const findAllResCount = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/base/classroom/findAllResCount'
export const getTeacherActAnalysisForIndex = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/lessonInfo/getTeacherActAnalysisForIndex'
export const getMultimediaRateForIndex = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/lessonInfo/getMultimediaRateForIndex'
export const getTeachingModel = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/teacherAnalysis/getTeachingModel'
export const getInteractionForIndex = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/lessonInfo/getInteractionForIndex'
export const getStudentAttendRateForIndex = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/lessonInfo/getStudentAttendRateForIndex'
export const getStudentStatusForIndex = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/lessonInfo/getStudentStatusForIndex'
export const findLessons = developUrl + '/control/course/findLessonsAndResourcesByCourseId'
export const getCourseById = developUrl + '/control/course/getCourseById'
export const findLessonsEventInfo = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/studentAnalysis/findLessonsEventInfo'
export const getAttendRateForEveryLesson =  (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/lessonInfo/getAttendRateForEveryLesson'
export const getStudentStatusForEveryLesson = (localStorage.getItem('moni')=="true"?'/moni':developUrl) + '/statistic/lessonInfo/getStudentStatusForEveryLesson'
